CDIR = ..
HDIR = ../../include

PREFIX = carte

CCW = /cygdrive/g/Programmes/Dev-Cpp/bin/g++.exe -D SDL_INCLUDE 
CCM = g++ -DMACOSX `sdl-config --cflags` -I"/System/Library/Frameworks/GLUT.framework/Headers" -I"/System/Library/Frameworks/OpenGL.framework/Headers" -I"../../include"
CC = $(CCW)
CFLAGSL = -Wall -g -I $(HDIR)
CFLAGS = -ansi $(CFLAGSL)
LEX = flex
LEXFLAGS = -Pyy$(PREFIX)
YACC = yacc
YACCFLAGS = -d -t -p yy$(PREFIX)


parser-lexer: $(PREFIX).parser.hpp $(PREFIX).parser.cpp $(PREFIX).lexer.cpp


all: $(PREFIX).global.o $(PREFIX).parser.o $(PREFIX).lexer.o $(PREFIX).o


clean:
	rm *~ *.o 

superclean: clean
	rm $(PREFIX)parser.hpp $(PREFIX)parser.cpp $(PREFIX)lexer.cpp


truc: truc.cpp
	$(CC) $(CFLAGS) -o truc.exe truc.cpp



$(PREFIX).o: $(PREFIX).global.hpp $(PREFIX).parser.hpp $(PREFIX).hpp $(PREFIX).cpp
	$(CC) $(CFLAGS) -c $(PREFIX).cpp


$(PREFIX).global.o: $(PREFIX).global.hpp $(PREFIX).global.cpp
	$(CC) $(CFLAGS) -c $(PREFIX).global.cpp


$(PREFIX).parser.o: $(PREFIX).parser.cpp $(PREFIX).global.hpp
	$(CC) $(CFLAGS) -c $(PREFIX).parser.cpp

$(PREFIX).parser.cpp: $(PREFIX).parser.y $(PREFIX).global.hpp
	$(YACC) $(YACCFLAGS) -o $(PREFIX).parser.cpp $(PREFIX).parser.y

$(PREFIX).parser.hpp: $(PREFIX).parser.cpp $(PREFIX).parser.h
	mv $(PREFIX).parser.h $(PREFIX).parser.hpp


# La compilation de lexer.c néceesite l'enlevement de l'option -ansi car la fonction int fileno(FILE *) est dans stdio.h sans être ANSI. 
$(PREFIX).lexer.o: $(PREFIX).global.hpp $(PREFIX).parser.hpp $(PREFIX).lexer.cpp
	$(CC) $(CFLAGSL) -c $(PREFIX).lexer.cpp

$(PREFIX).lexer.cpp: $(PREFIX).global.hpp $(PREFIX).parser.hpp $(PREFIX).lexer.l
	$(LEX) $(LEXFLAGS) -o$(PREFIX).lexer.cpp $(PREFIX).lexer.l
