#line 2 "pascal.lexer.cpp"

#line 4 "pascal.lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer yypascal_create_buffer
#define yy_delete_buffer yypascal_delete_buffer
#define yy_flex_debug yypascal_flex_debug
#define yy_init_buffer yypascal_init_buffer
#define yy_flush_buffer yypascal_flush_buffer
#define yy_load_buffer_state yypascal_load_buffer_state
#define yy_switch_to_buffer yypascal_switch_to_buffer
#define yyin yypascalin
#define yyleng yypascalleng
#define yylex yypascallex
#define yylineno yypascallineno
#define yyout yypascalout
#define yyrestart yypascalrestart
#define yytext yypascaltext
#define yywrap yypascalwrap
#define yyalloc yypascalalloc
#define yyrealloc yypascalrealloc
#define yyfree yypascalfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yypascalrestart(yypascalin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yypascalleng;

extern FILE *yypascalin, *yypascalout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yypascaltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yypascaltext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yypascalrestart()), so that the user can continue scanning by
	 * just pointing yypascalin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yypascaltext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yypascalleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yypascalwrap()'s to do buffer switches
 * instead of setting up a fresh yypascalin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yypascalrestart (FILE *input_file  );
void yypascal_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yypascal_create_buffer (FILE *file,int size  );
void yypascal_delete_buffer (YY_BUFFER_STATE b  );
void yypascal_flush_buffer (YY_BUFFER_STATE b  );
void yypascalpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypascalpop_buffer_state (void );

static void yypascalensure_buffer_stack (void );
static void yypascal_load_buffer_state (void );
static void yypascal_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yypascal_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yypascal_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yypascal_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yypascal_scan_bytes (yyconst char *bytes,int len  );

void *yypascalalloc (yy_size_t  );
void *yypascalrealloc (void *,yy_size_t  );
void yypascalfree (void *  );

#define yy_new_buffer yypascal_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yypascalensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yypascal_create_buffer(yypascalin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yypascalensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yypascal_create_buffer(yypascalin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yypascalwrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yypascalin = (FILE *) 0, *yypascalout = (FILE *) 0;

typedef int yy_state_type;

extern int yypascallineno;

int yypascallineno = 1;

extern char *yypascaltext;
#define yytext_ptr yypascaltext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yypascaltext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yypascalleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 34
#define YY_END_OF_BUFFER 35
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[48] =
    {   0,
        0,    0,   35,   33,    2,    1,   33,   24,   33,    7,
        9,   13,   11,   29,   12,   30,   33,    4,   27,   28,
       19,   18,   20,    8,   10,   23,   33,    2,    0,    6,
        0,   16,   14,   15,   32,   26,   17,    0,    4,   25,
       21,   31,   22,    0,    3,    5,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    5,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   17,   18,
       19,   20,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       21,    1,   22,   23,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   24,    1,   25,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[26] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[52] =
    {   0,
        0,    0,   56,   57,   53,   57,   50,   57,   47,   57,
       57,   39,   38,   57,   13,   37,    0,   14,   30,   57,
       11,   57,   29,   57,   57,   57,   22,   44,   41,   57,
       38,   57,   57,   57,   57,   57,   57,   28,   19,   57,
       57,   57,   57,   17,   57,   26,   57,   34,   36,   27,
       38
    } ;

static yyconst flex_int16_t yy_def[52] =
    {   0,
       47,    1,   47,   47,   47,   47,   48,   47,   49,   47,
       47,   47,   47,   47,   47,   47,   50,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   51,   47,   48,   47,
       49,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   51,   47,   47,    0,   47,   47,   47,
       47
    } ;

static yyconst flex_int16_t yy_nxt[83] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,    4,   34,   38,   37,   39,   41,
       42,   38,   35,   39,   29,   29,   31,   31,   44,   44,
       46,   45,   46,   30,   30,   28,   45,   43,   40,   36,
       33,   32,   30,   30,   28,   47,    3,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47
    } ;

static yyconst flex_int16_t yy_chk[83] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   15,   18,   50,   18,   21,
       21,   39,   15,   39,   48,   48,   49,   49,   51,   51,
       46,   44,   38,   31,   29,   28,   27,   23,   19,   16,
       13,   12,    9,    7,    5,    3,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yypascal_flex_debug;
int yypascal_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yypascaltext;
#line 1 "pascal.lexer.l"
#line 2 "pascal.lexer.l"

  // Fichier lexer du compilateur PASCAL et de la machine virtuelle PASCAL.


#include "global.hpp"
#include "pascal/pascal.tools.hpp"
#include "pascal/pascal.expr.hpp"
#include "pascal/pascal.parser.hpp"


/* yypascaltext yypascalleng ECHO */
/* Pour faire le pipe, on fait option + maj + l
   Maintenant, on chercher le tilde. option + n + espace */
/* Le tilde, il faut faire option + n + la touche appropriee. */

  static int nb_lignes = 0, nb_char_ligne = 0, nb_char_tot = 0;

  // La file des TOKEN.
  struct stoken {
    int token;
    YYSTYPE yylval;
    unsigned int nb_lignes, nb_char_ligne, nb_char_tot, longueur;
  };
    
  static class pfifo<stoken> *tokens = NULL;

  static int match_symbol(void);


#define TAILLE_TAMPON_SYMBOLE_MAX 4095
  static char symbole[TAILLE_TAMPON_SYMBOLE_MAX + 1];
  static unsigned int taille_tampon_symbole = 0;



  void yypascallexerinit(void) {
    nb_lignes = 0, nb_char_ligne = 0, nb_char_tot = 0;
    while (tokens != NULL) delete popf(tokens);
    taille_tampon_symbole = 0;
  }




  static const char * const string_of_token(int token) {
    switch (token) {
    case TOKEN_EOF: return "EOF"; break;
    case TOKEN_TRUE: return "TRUE"; break;
    case TOKEN_FALSE: return "FALSE"; break;
    case TOKEN_IDENT: return "IDENT"; break;
    case TOKEN_AND: return "AND"; break;
    case TOKEN_OR: return "OR"; break;
    case TOKEN_NOT: return "NOT"; break;
    case TOKEN_IF: return "IF"; break;
    case TOKEN_THEN: return "THEN"; break;
    case TOKEN_ELSE: return "ELSE"; break;
    case TOKEN_BEGIN: return "BEGIN"; break;
    case TOKEN_END: return "END"; break;
    case TOKEN_WHILE: return "WHILE"; break;
    case TOKEN_DO: return "DO"; break;
    case TOKEN_REPEAT: return "REPEAT"; break;
    case TOKEN_UNTIL: return "UNTIL"; break;
    case TOKEN_FOR: return "FOR"; break;
    case TOKEN_TO: return "TO"; break;
    case TOKEN_IPLUS: return "IPLUS"; break;
    case TOKEN_IMOINS: return "IMOINS"; break;
    case TOKEN_IMULT: return "IMULT"; break;
    case TOKEN_IDIV: return "DIV"; break;
    case TOKEN_IMOD: return "IMOD"; break;
    case TOKEN_RPLUS: return "RPLUS"; break;
    case TOKEN_RMOINS: return "RMOINS"; break;
    case TOKEN_RMULT: return "RMULT"; break;
    case TOKEN_RDIV: return "RDIV"; break;
    case TOKEN_ENTIER: return "ENTIER"; break;
    case TOKEN_REEL: return "REEL"; break;
    case TOKEN_PTVIRG: return "POINT VIRGULE"; break;
    case TOKEN_CHAINE: return "CHAINE"; break;
    case TOKEN_OPENPAR: return "PARENTHESE OUVRANTE"; break;
    case TOKEN_CLOSEPAR: return "PARENTHESE FERMANTE"; break;
    case TOKEN_BLANC: return "BLANCS"; break;
    case TOKEN_COMMENT: return "COMMENTAIRE"; break;
    case TOKEN_EQUAL: return "EQUAL"; break;
    case TOKEN_INF: return "INF"; break;
    case TOKEN_SUP: return "SUP"; break;
    case TOKEN_INFEQ: return "INFEQ"; break;
    case TOKEN_SUPEQ: return "SUPEQ"; break;
    case TOKEN_TYPE: return "TYPE"; break;
    case TOKEN_PTR: return "PTR"; break;
    case TOKEN_REF: return "REF"; break;
    case TOKEN_ARRAY: return "ARRAY"; break;
    case TOKEN_OF: return "OF"; break;
    case TOKEN_RECORD: return "RECORD"; break;
    case TOKEN_AFFECTATION: return "AFFECTATION"; break;
    case TOKEN_WRITE: return "WRITE"; break;
    case TOKEN_WRITELN: return "WRITELN"; break;
    case TOKEN_READ: return "READ"; break;
    case TOKEN_READLN: return "READLN"; break;
    case TOKEN_DEUXPOINTS: return "DEUX POINTS"; break;
    case TOKEN_OPENBRACKET: return "CROCHET OUVRANT"; break;
    case TOKEN_CLOSEBRACKET: return "CROCHET FERMANT"; break;
    case TOKEN_VAR: return "VAR"; break;
    case TOKEN_CONST: return "CONST"; break;
    case TOKEN_BOOLEAN: return "BOOLEAN"; break;
    case TOKEN_INTEGER: return "INTEGER"; break;
    case TOKEN_SUBRANGE: return "SUBRANGE"; break;
    case TOKEN_REAL: return "REAL"; break;
    case TOKEN_PROCEDURE: return "PROCEDURE"; break;
    case TOKEN_FUNCTION: return "FUNCTION"; break;
    case TOKEN_VIRGULE: return "VIRGULE"; break;
    case TOKEN_POINT: return "POINT"; break;
    case TOKEN_DIFF: return "DIFF"; break;
    case TOKEN_NIL: return "NIL"; break;
    case TOKEN_NEW: return "NEW"; break;
    case TOKEN_MUSIQUE: return "MUSIQUE"; break;
    case TOKEN_MENU: return "MENU"; break;
    case TOKEN_ITEM: return "ITEM"; break;
    case TOKEN_STRING: return "STRING"; break;

    case TOKEN_FLECHE: return "FLECHE"; break;
      //case TOKEN_HEROS: return "HEROS"; break;
    case TOKEN_CAMERA: return "CAMERA"; break;
    case TOKEN_WAIT: return "WAIT"; break;
    case TOKEN_HALT: return "HALT"; break;
    case TOKEN_RESTART: return "RESTART"; break;
    case TOKEN_FONDU: return "FONDU"; break;
    case TOKEN_RECOBJET: return "RECEVOIROBJET"; break;
    case TOKEN_RECARME: return "RECEVOIRARME"; break;
    case TOKEN_SUPOBJET: return "SUPPRIMEROBJET"; break;
    case TOKEN_CARTE: return "CARTE"; break;
    case TOKEN_SETPOSITION: return "SETPOSITION"; break;
    case TOKEN_DEPLACER: return "DEPLACER"; break;
    case TOKEN_SETPOSITIONZ: return "SETPOSITIONZ"; break;
    case TOKEN_DEPLACERZ: return "DEPLACER"; break;
    case TOKEN_ROTATE: return "ROTATE"; break;
    case TOKEN_SOLIDARISER: return "SOLIDARISER"; break;
    case TOKEN_DESOLIDARISER: return "DESOLIDARISER"; break;
    case TOKEN_DEFAUT: return "DEFAUT"; break;
    case TOKEN_ZOOM: return "ZOOM"; break;
    case TOKEN_FRAPPER: return "FRAPPER"; break;
    case TOKEN_AJOUTERANIME: return "AJOUTERANIME"; break;
    case TOKEN_AJOUTERNONANIME: return "AJOUTERNONANIME"; break;
    case TOKEN_SETTEMPS: return "SETTEMPS"; break;
    case TOKEN_SETORIENTATION: return "SETORIENTATION"; break;
    case TOKEN_NOMCARTE: return "NOMCARTE"; break;
    case TOKEN_WAITFOR: return "WAITFOR"; break;
    case TOKEN_BLOQUERTEMPS: return "BLOQUERTEMPS"; break;
    case TOKEN_DEBLOQUERTEMPS: return "DEBLOQUERTEMPS"; break;
    case TOKEN_CARTEZ: return "CARTEZ"; break;
    default:
      return "INCONNU";
    }
  }



#define _PRINT_OUT(a,b,c)						\
  {									\
    fprintf(yypascalout, "{{ symbole %s [ %s ] }}", string_of_token(a), (b));	\
    fflush(yypascalout);                                                      \
    nb_char_tot += (c);							\
    nb_char_ligne += (c);						\
  }

#define __PRINT_OUT(a)  						\
  {									\
    fprintf(yypascalout, "\n---> symbole %s \n", string_of_token(a));         \
  }

#define PRINT_OUT(a,b)											\
  {													\
    {													\
      if (taille_tampon_symbole > 0)									\
	{												\
	  struct stoken* temp;										\
	  temp = new struct stoken;									\
	  temp->nb_lignes = nb_lignes;									\
	  temp->nb_char_ligne = nb_char_ligne;								\
	  temp->nb_char_tot = nb_char_tot;								\
	  temp->longueur = taille_tampon_symbole;							\
	  temp->token = match_symbol();									\
	  {												\
	    if (temp->token == TOKEN_IDENT)								\
	      {                                                         				\
		temp->yylval.token.val.ident = strcpy(new char[taille_tampon_symbole + 1], symbole);	\
              }                            								\
          }												\
	  tokens = mf(temp, tokens);									\
	  _PRINT_OUT(temp->token, symbole, taille_tampon_symbole);					\
	  taille_tampon_symbole = 0;									\
	}												\
    }													\
    _PRINT_OUT(a, b, yypascalleng);										\
  }													\



#define DO_ACTION(TOKEN,TEXT,WHAT)              \
  {						\
  struct stoken  *temp;				\
						\
  PRINT_OUT(TOKEN, TEXT);                       \
						\
  temp = new struct stoken;			\
  temp->token = TOKEN;				\
  temp->yylval.token.val.WHAT; 		        \
  temp->nb_lignes = nb_lignes;			\
  temp->nb_char_ligne = nb_char_ligne;		\
  temp->nb_char_tot = nb_char_tot;		\
  temp->longueur = yypascalleng;       		\
			                        \
  tokens = mf(temp, tokens);			\
						\
  temp = popf(tokens);				\
						\
  yypascallval = temp->yylval;			\
  int ret =  temp->token;			\
  delete temp;					\
  __PRINT_OUT(ret);                             \
  return ret;					\
}





  // Fonction qui matche un symbole, le convertit en minuscule 
  // (le langage est case insensitive pour les mots-clefs,
  // mais pas pour le reste).
  static int match_symbol(void) {
    symbole[taille_tampon_symbole] = '\0';

    if (strcasecmp("not", symbole) == 0) {return TOKEN_NOT;}
    else if (strcasecmp("true"   , symbole) == 0) {return TOKEN_TRUE;}
    else if (strcasecmp("false"  , symbole) == 0) {return TOKEN_FALSE;}
    else if (strcasecmp("and"    , symbole) == 0) {return TOKEN_AND;}
    else if (strcasecmp("or"     , symbole) == 0) {return TOKEN_OR;}
    else if (strcasecmp("div"    , symbole) == 0) {return TOKEN_IDIV;}
    else if (strcasecmp("mod"    , symbole) == 0) {return TOKEN_IMOD;}
    else if (strcasecmp("if"     , symbole) == 0) {return TOKEN_IF;}
    else if (strcasecmp("then"   , symbole) == 0) {return TOKEN_THEN;}
    else if (strcasecmp("else"   , symbole) == 0) {return TOKEN_ELSE;}
    else if (strcasecmp("while"  , symbole) == 0) {return TOKEN_WHILE;}
    else if (strcasecmp("do"     , symbole) == 0) {return TOKEN_DO;}
    else if (strcasecmp("for"    , symbole) == 0) {return TOKEN_FOR;}
    else if (strcasecmp("to"     , symbole) == 0) {return TOKEN_TO;}
    else if (strcasecmp("begin"  , symbole) == 0) {return TOKEN_BEGIN;}
    else if (strcasecmp("var"    , symbole) == 0) {return TOKEN_VAR;}
    else if (strcasecmp("end"    , symbole) == 0) {return TOKEN_END;}
    else if (strcasecmp("repeat" , symbole) == 0) {return TOKEN_REPEAT;}
    else if (strcasecmp("until"  , symbole) == 0) {return TOKEN_UNTIL;}
    else if (strcasecmp("type"   , symbole) == 0) {return TOKEN_TYPE;}
    else if (strcasecmp("boolean", symbole) == 0) {return TOKEN_BOOLEAN;}
    else if (strcasecmp("integer", symbole) == 0) {return TOKEN_INTEGER;}
    else if (strcasecmp("real"   , symbole) == 0) {return TOKEN_REAL;}
    else if (strcasecmp("string" , symbole) == 0) {return TOKEN_STRING;}
    else if (strcasecmp("array"  , symbole) == 0) {return TOKEN_ARRAY;}
    else if (strcasecmp("of"     , symbole) == 0) {return TOKEN_OF;}
    else if (strcasecmp("record" , symbole) == 0) {return TOKEN_RECORD;}
    else if (strcasecmp("write"  , symbole) == 0) {return TOKEN_WRITE;}
    else if (strcasecmp("writeln", symbole) == 0) {return TOKEN_WRITELN;}
    else if (strcasecmp("read"   , symbole) == 0) {return TOKEN_READ;}
    else if (strcasecmp("readln" , symbole) == 0) {return TOKEN_READLN;}
    else if (strcasecmp("const"  , symbole) == 0) {return TOKEN_CONST;}
    else if (strcasecmp("procedure", symbole) == 0) {return TOKEN_PROCEDURE;}
    else if (strcasecmp("function", symbole) == 0) {return TOKEN_FUNCTION;}
    else if (strcasecmp("virgule", symbole) == 0) {return TOKEN_VIRGULE;}
    else if (strcasecmp("nil"    , symbole) == 0) {return TOKEN_NIL;}
    else if (strcasecmp("new"    , symbole) == 0) {return TOKEN_NEW;}
    else if (strcasecmp("musique", symbole) == 0) {return TOKEN_MUSIQUE;}
    else if (strcasecmp("menu"   , symbole) == 0) {return TOKEN_MENU;}
    else if (strcasecmp("item"   , symbole) == 0) {return TOKEN_ITEM;}

    //    else if (strcasecmp("héros"         , symbole) == 0) {return TOKEN_HEROS;}
    //else if (strcasecmp("heros"         , symbole) == 0) {return TOKEN_HEROS;}
    else if (strcasecmp("caméra"        , symbole) == 0) {return TOKEN_CAMERA;}
    else if (strcasecmp("camera"        , symbole) == 0) {return TOKEN_CAMERA;}
    else if (strcasecmp("wait"          , symbole) == 0) {return TOKEN_WAIT;}
    else if (strcasecmp("halt"          , symbole) == 0) {return TOKEN_HALT;}
    else if (strcasecmp("restart"       , symbole) == 0) {return TOKEN_RESTART;}
    else if (strcasecmp("fondu"         , symbole) == 0) {return TOKEN_FONDU;}
    else if (strcasecmp("recevoirobjet" , symbole) == 0) {return TOKEN_RECOBJET;}
    else if (strcasecmp("recevoirarme"  , symbole) == 0) {return TOKEN_RECARME;}
    else if (strcasecmp("supprimerobjet", symbole) == 0) {return TOKEN_SUPOBJET;}
    else if (strcasecmp("carte"         , symbole) == 0) {return TOKEN_CARTE;}
    else if (strcasecmp("setposition"   , symbole) == 0) {return TOKEN_SETPOSITION;}
    else if (strcasecmp("setpositionz"  , symbole) == 0) {return TOKEN_SETPOSITIONZ;}
    else if (strcasecmp("deplacer"      , symbole) == 0) {return TOKEN_DEPLACER;}
    else if (strcasecmp("déplacer"      , symbole) == 0) {return TOKEN_DEPLACER;}
    else if (strcasecmp("deplacerz"     , symbole) == 0) {return TOKEN_DEPLACERZ;}
    else if (strcasecmp("déplacerz"     , symbole) == 0) {return TOKEN_DEPLACERZ;}
    else if (strcasecmp("rotate"        , symbole) == 0) {return TOKEN_ROTATE;}
    else if (strcasecmp("solidariser"   , symbole) == 0) {return TOKEN_SOLIDARISER;}
    else if (strcasecmp("désolidariser" , symbole) == 0) {return TOKEN_DESOLIDARISER;}
    else if (strcasecmp("desolidariser" , symbole) == 0) {return TOKEN_DESOLIDARISER;}
    else if (strcasecmp("defaut"        , symbole) == 0) {return TOKEN_DEFAUT;}
    else if (strcasecmp("défaut"        , symbole) == 0) {return TOKEN_DEFAUT;}
    else if (strcasecmp("zoom"          , symbole) == 0) {return TOKEN_ZOOM;}
    else if (strcasecmp("frapper"       , symbole) == 0) {return TOKEN_FRAPPER;}
    else if (strcasecmp("ajouteranime"  , symbole) == 0) {return TOKEN_AJOUTERANIME;}
    else if (strcasecmp("ajouternonanime", symbole) == 0) {return TOKEN_AJOUTERNONANIME;}
    else if (strcasecmp("settemps"      , symbole) == 0) {return TOKEN_SETTEMPS;}
    else if (strcasecmp("setorientation", symbole) == 0) {return TOKEN_SETORIENTATION;}
    else if (strcasecmp("nomcarte"      , symbole) == 0) {return TOKEN_NOMCARTE;}
    else if (strcasecmp("waitfor"       , symbole) == 0) {return TOKEN_WAITFOR;}
    else if (strcasecmp("bloquertemps"  , symbole) == 0) {return TOKEN_BLOQUERTEMPS;}
    else if (strcasecmp("debloquertemps", symbole) == 0) {return TOKEN_DEBLOQUERTEMPS;}
    else if (strcasecmp("cartez"        , symbole) == 0) {return TOKEN_CARTEZ;}
    else {return TOKEN_IDENT;}
  }



//reel ({entier}\.{chiffre}*)|({chiffre}*\.{entier})
// En l'occurrence, comme j'ai une interface avec une file de tokens,
// je recommence tout le temps en rempilant à chaque fois.
// NON. En fait, on fait comme avant.
// Ce qui permet de matcher la règle <<EOF>> comme toutes les autres.
// ter   {						
//   struct stoken  *temp;				
//   PRINT_OUT(TOKEN_EGAL, "TEXT");                       
//   temp = new struct stoken;			
//   temp->token = TOKEN_EGAL;				
//   temp->yylval.entier = 0;				
//   temp->nb_lignes = nb_lignes;			
//   temp->nb_char_ligne = nb_char_ligne;		
//   temp->nb_char_tot = nb_char_tot;		
//   tokens = mf(temp, tokens);			
//   temp = tokens->a;				
//   //tokens = tokens->suivant;			
//   tokens->a = tokens->suivant->a;               
//   tokens->suivant = tokens->suivant->suivant;   
//   yypascallval = temp->yylval;			
//   int ret =  temp->token;			
//   delete temp;					
//   return ret;					
// }
#line 841 "pascal.lexer.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yypascallex_destroy (void );

int yypascalget_debug (void );

void yypascalset_debug (int debug_flag  );

YY_EXTRA_TYPE yypascalget_extra (void );

void yypascalset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yypascalget_in (void );

void yypascalset_in  (FILE * in_str  );

FILE *yypascalget_out (void );

void yypascalset_out  (FILE * out_str  );

int yypascalget_leng (void );

char *yypascalget_text (void );

int yypascalget_lineno (void );

void yypascalset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yypascalwrap (void );
#else
extern int yypascalwrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yypascaltext, yypascalleng, 1, yypascalout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yypascalin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yypascalin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yypascalin))==0 && ferror(yypascalin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yypascalin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yypascallex (void);

#define YY_DECL int yypascallex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yypascaltext and yypascalleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 397 "pascal.lexer.l"



#line 1025 "pascal.lexer.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yypascalin )
			yypascalin = stdin;

		if ( ! yypascalout )
			yypascalout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yypascalensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yypascal_create_buffer(yypascalin,YY_BUF_SIZE );
		}

		yypascal_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yypascaltext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 48 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 57 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case YY_STATE_EOF(INITIAL):
#line 400 "pascal.lexer.l"
DO_ACTION(TOKEN_EOF, "EOF", entier = 0);
	YY_BREAK
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 402 "pascal.lexer.l"
PRINT_OUT(TOKEN_BLANC, "EOL"); nb_lignes++; nb_char_ligne = 0;// yypascalcontinue();
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 404 "pascal.lexer.l"
PRINT_OUT(TOKEN_BLANC, yypascaltext); //yycontinue();
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 406 "pascal.lexer.l"
PRINT_OUT(TOKEN_COMMENT, yypascaltext); //yycontinue();
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 408 "pascal.lexer.l"
DO_ACTION(TOKEN_ENTIER,yypascaltext,entier = atoi(yypascaltext));
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 410 "pascal.lexer.l"
DO_ACTION(TOKEN_REEL,yypascaltext,reel = ((double) atof(yypascaltext)));
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 412 "pascal.lexer.l"
{
                 char *ctemp;
		 ctemp = new char [yypascalleng - 2 + 1];
		 strncpy(ctemp, &(yypascaltext[1]), yypascalleng - 2);
		 ctemp[yypascalleng - 2] = '\0';
		 DO_ACTION(TOKEN_CHAINE,yypascaltext,chaine = ctemp);
               }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 420 "pascal.lexer.l"
DO_ACTION(TOKEN_OPENPAR,yypascaltext,entier = 0);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 422 "pascal.lexer.l"
DO_ACTION(TOKEN_OPENBRACKET,yypascaltext,entier = 0);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 424 "pascal.lexer.l"
DO_ACTION(TOKEN_CLOSEPAR,yypascaltext,entier = 0);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 426 "pascal.lexer.l"
DO_ACTION(TOKEN_CLOSEBRACKET,yypascaltext,entier = 0);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 428 "pascal.lexer.l"
DO_ACTION(TOKEN_IPLUS,yypascaltext,entier = 0);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 430 "pascal.lexer.l"
DO_ACTION(TOKEN_IMOINS,yypascaltext,entier = 0);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 432 "pascal.lexer.l"
DO_ACTION(TOKEN_IMULT,yypascaltext,entier = 0);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 434 "pascal.lexer.l"
DO_ACTION(TOKEN_RPLUS,yypascaltext,entier = 0);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 436 "pascal.lexer.l"
DO_ACTION(TOKEN_RMOINS,yypascaltext,entier = 0);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 438 "pascal.lexer.l"
DO_ACTION(TOKEN_RMULT,yypascaltext,entier = 0);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 440 "pascal.lexer.l"
DO_ACTION(TOKEN_RDIV,yypascaltext,entier = 0);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 442 "pascal.lexer.l"
DO_ACTION(TOKEN_EQUAL,yypascaltext,entier = 0);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 444 "pascal.lexer.l"
DO_ACTION(TOKEN_INF,yypascaltext,entier = 0);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 446 "pascal.lexer.l"
DO_ACTION(TOKEN_SUP,yypascaltext,entier = 0);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 448 "pascal.lexer.l"
DO_ACTION(TOKEN_INFEQ,yypascaltext,entier = 0);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 450 "pascal.lexer.l"
DO_ACTION(TOKEN_SUPEQ,yypascaltext,entier = 0);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 452 "pascal.lexer.l"
DO_ACTION(TOKEN_PTR,yypascaltext,entier = 0);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 454 "pascal.lexer.l"
DO_ACTION(TOKEN_REF,yypascaltext,entier = 0);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 456 "pascal.lexer.l"
DO_ACTION(TOKEN_AFFECTATION,yypascaltext,entier = 0);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 458 "pascal.lexer.l"
DO_ACTION(TOKEN_SUBRANGE,yypascaltext,entier = 0);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 460 "pascal.lexer.l"
DO_ACTION(TOKEN_DEUXPOINTS,yypascaltext,entier = 0);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 462 "pascal.lexer.l"
DO_ACTION(TOKEN_PTVIRG,yypascaltext,entier = 0);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 464 "pascal.lexer.l"
DO_ACTION(TOKEN_VIRGULE,yypascaltext,entier = 0);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 466 "pascal.lexer.l"
DO_ACTION(TOKEN_POINT,yypascaltext,entier = 0);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 468 "pascal.lexer.l"
DO_ACTION(TOKEN_DIFF,yypascaltext,entier = 0);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 470 "pascal.lexer.l"
DO_ACTION(TOKEN_FLECHE,yypascaltext,entier = 0);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 473 "pascal.lexer.l"
{
                 if (taille_tampon_symbole >= TAILLE_TAMPON_SYMBOLE_MAX) {
		   fprintf(yypascalout, "Erreur de lexing. On a un symbole de plus de %u caractères. On skippe le caractère '%s'.", TAILLE_TAMPON_SYMBOLE_MAX, yypascaltext);
		 }
		 else {
		   symbole[taille_tampon_symbole++] = yypascaltext[0];
		 }
		 //yycontinue();
               }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 483 "pascal.lexer.l"
ECHO;
	YY_BREAK
#line 1299 "pascal.lexer.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yypascalin at a new source and called
			 * yypascallex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yypascalin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yypascalwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yypascaltext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yypascallex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yypascalrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yypascalrestart(yypascalin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yypascalrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 48 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 48 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 47);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yypascalrestart(yypascalin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yypascalwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yypascaltext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yypascalrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yypascalensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yypascal_create_buffer(yypascalin,YY_BUF_SIZE );
	}

	yypascal_init_buffer(YY_CURRENT_BUFFER,input_file );
	yypascal_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yypascal_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypascalpop_buffer_state();
	 *		yypascalpush_buffer_state(new_buffer);
     */
	yypascalensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yypascal_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yypascalwrap()) processing, but the only time this flag
	 * is looked at is after yypascalwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yypascal_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yypascalin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yypascal_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yypascalalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yypascal_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yypascalalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yypascal_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yypascal_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yypascal_create_buffer()
 * 
 */
    void yypascal_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yypascalfree((void *) b->yy_ch_buf  );

	yypascalfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yypascalrestart() or at EOF.
 */
    static void yypascal_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yypascal_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yypascal_init_buffer was _probably_
     * called from yypascalrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yypascal_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yypascal_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypascalpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yypascalensure_buffer_stack();

	/* This block is copied from yypascal_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yypascal_switch_to_buffer. */
	yypascal_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypascalpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yypascal_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yypascal_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yypascalensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yypascalalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yypascalensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yypascalrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yypascalensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yypascal_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yypascalalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yypascal_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yypascal_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yypascallex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yypascal_scan_bytes() instead.
 */
YY_BUFFER_STATE yypascal_scan_string (yyconst char * yystr )
{
    
	return yypascal_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yypascallex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yypascal_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yypascalalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yypascal_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yypascal_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yypascal_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yypascaltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yypascaltext[yypascalleng] = (yy_hold_char); \
		(yy_c_buf_p) = yypascaltext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yypascalleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yypascalget_lineno  (void)
{
        
    return yypascallineno;
}

/** Get the input stream.
 * 
 */
FILE *yypascalget_in  (void)
{
        return yypascalin;
}

/** Get the output stream.
 * 
 */
FILE *yypascalget_out  (void)
{
        return yypascalout;
}

/** Get the length of the current token.
 * 
 */
int yypascalget_leng  (void)
{
        return yypascalleng;
}

/** Get the current token.
 * 
 */

char *yypascalget_text  (void)
{
        return yypascaltext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yypascalset_lineno (int  line_number )
{
    
    yypascallineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yypascal_switch_to_buffer
 */
void yypascalset_in (FILE *  in_str )
{
        yypascalin = in_str ;
}

void yypascalset_out (FILE *  out_str )
{
        yypascalout = out_str ;
}

int yypascalget_debug  (void)
{
        return yypascal_flex_debug;
}

void yypascalset_debug (int  bdebug )
{
        yypascal_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yypascallex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yypascalin = stdin;
    yypascalout = stdout;
#else
    yypascalin = (FILE *) 0;
    yypascalout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yypascallex_init()
     */
    return 0;
}

/* yypascallex_destroy is for both reentrant and non-reentrant scanners. */
int yypascallex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yypascal_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypascalpop_buffer_state();
	}

	/* Destroy the stack itself. */
	yypascalfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yypascallex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yypascalalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yypascalrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yypascalfree (void * ptr )
{
	free( (char *) ptr );	/* see yypascalrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 483 "pascal.lexer.l"


/*
// Fonction qui est appelée lorsque EOF est atteint.
// Retourne 0 (false) si on continue.
// Sinon, ça termine et renvoie 0 à l'appelant.
// %option noyywrap --> scanner behave as if it returns always true (1).
//
// La règle spéciale <<EOF>> est matchée lorsqu'on rencontre une fin de fichier,
// et que la fonction yypascalwrap() retourne vrai (valeur différente de zéro ; i.e.,
// no further file to process).
//yypascalwrap(){}
*/

